### ISSUE TITLE
Cannot enable WiFi on new (2019-12-20) image

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#109]
**Describe the bug**
I cannot enable WiFi on a newly flashed image.

**To Reproduce**
Steps to reproduce the behaviour:
1. Flash 2019-12-20-zynthianos-buster-lite-1.0.0 image
2. Connect network cable to LAN and boot Zynthian
3. Connect to webconf and add WiFi configuration
4. Enable WiFi
5 WiFi fails to enable

**Expected behaviour**
WiFi should enable and connect to LAN.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: 2019-12-20
Memory: 9% (363M/3906M)
SD Card: 44% (12G/28G)
Temperature: 33.0ºC

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (a000211)
zynthian-sys: master (7ecb396)
zynthian-data: master (3d44cc8)
zynthian-webconf: master (30d3cc4)

**Additional context**
This is a fresh install of 2019-12-20-zynthianos-buster-lite-1.0.0 image. 2019-12-19-zynthianos-buster-lite-1.0.0 image worked okay.

**Comment by riban-bw** [comment]
Enabled WiFi Hotspot then disabled and now WiFi works.

**Comment by jofemodo** [comment]
It works for me. I can't reproduce with the same SD image.
I have solved a couple of WIFI-related issues (#121 & #134), that were producing random problems. I I think this issue is caused by one of these issues, so i will close.
Of course, i would like to have confirmation, so if you want to kindly test with a fresh-burned image ...
