### ISSUE TITLE
Cannot add more than one Pianoteq layer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#111]
**Describe the bug**
After adding Pianoteq as a layer, it disappears from the list of available engines so cannot add a second Painoteq layer.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Pianoteq layer
2. Add layer
3. Pianoteq not in list of available engines

**Expected behaviour**
Pianoteq is available in list.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: Generic HDMI Display
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
OS: Raspbian GNU/Linux 10 (buster)
Build Date: 2019-12-20
Memory: 9% (371M/3906M)
SD Card: 44% (12G/28G)
Temperature: 32.0ºC

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (a000211)
zynthian-sys: master (7ecb396)
zynthian-data: master (3d44cc8)
zynthian-webconf: master (30d3cc4)

**Comment by jofemodo** [comment]
Some engines are allowed to have one instance only:

+ Aeolus
+ setBfree
+ PureData
+ MOD-UI
+ Pianoteq 

Aeolus & setBfree, as currently implemented, optimized for on-stage/live performance, are difficult to manage as multi-instance engines.
MOD-UI has no sense as muti-instance engine and it would require modifying the code "quite a bit".

Pianoteq, as standalone engine, is also limited to 1 instance because the high CPU consumption. I've not thought about muti-instance considerations because until the RBPi4, a single instance consumed all CPU resources. I doubt you can run 2 Pianoteq instances in a RBPi4, but of course, you are free of trying and if it's possible and there is a use case, i would consider to implement a multi-instance engine. 

Regarding PD, I would like to improve it and turning it into a multi-instance engine ...

Finally, remember that you can run setBfree and Pianoteq as LV2 plugins ...

**Comment by riban-bw** [comment]
I looked in the wiki for info on which plugins have such constraints but did not find it. Maybe your useful description could be added to the wiki?

I can run multiple instances of Pianoteq as LV2 plugins - thank for the tip, but how do I define which instrument is loaded? It seems to always load the same piano.

**Comment by jofemodo** [comment]
It's covered in the user guide:

https://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#Engine_Selection

Regarding running Pianoteq as a plugin, i think currently there are no LV2 presets defined anywhere. It should be done ...
