### ISSUE TITLE
Issue: stuck keystrokes behaviour on bookworm

### ISSUE THREAD

**Issue by ivan1071** [zynthian/zynthian-issue-tracking#1175]
# Describe the issue
On bookworm image with some configurable keypads  zynpot key  bindings remain stuck on last input, except for "select" zynpot who works the right way. With normal keyboard everything turns fine. 
No issue on Buster image

# To Reproduce
simply attach keypad configured with expected keybindings. (**sayodevice 6x4** in my case)
Issue is shown whenever there is a function with a changing value:
-- mixer page: volume/pan on selected chain
-- chain control page: any corresponding variable knob. (Excluding "Select" )

NOTE: same issue happens on a custom rpi5 zynthian with no buttons, encoders or dedicated hardware and bookworm installed.

# Configuration
## Hardware
```
Raspberry Pi 3 Model B Rev 1.2
Audio: HifiBerry DAC+
Display: PiTFT 2.8 Resistive
Wiring: PROTOTYPE-4
I2C: MCP23008@0x20
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-06-26
Memory: 57% (522M/907M)
SD Card: 47% (13G/29G)
Temperature: 55.3ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: 16
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (628f3fb) 
zynthian-ui: oram (95067da)
zynthian-sys: oram (4461148)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (f31699f)
```

**Comment by riban-bw** [comment]
This appears to be the USB HID (keyboard) sending keycodes in the wrong order, e.g.

- CTRL press
- Key press
- CTRL release
- Key release

Because the CTRL modifier is released before the key is released, zynthian does not see the CTRL+key release message. The zynthian behaviour is to lock the key press until it receives the CTRL+key release message. This is by design.

It looks like a flawed implementation of the USB keypad. If this is found to be more prolific, we could consider changing the behaviour of zynthian, e.g. to ignore modifiers on release. (Not quite that simple!)
