### ISSUE TITLE
Internet radio component / Stations change

### ISSUE THREAD

**Issue by WWDTC** [zynthian/zynthian-issue-tracking#1209]
Seems that multiple chains (with different radio stations) can be added, but only last choosen station plays in reality (oram 20240928). There is no clear way to quickly change stations.

How to reproduce:

Add Audio Generator chain - Internet Radio.
Choose station, Zynthian adds audio chain to mixer and starts playing.
Add another Audio Generator chain - Internet Radio.
Choose another station, Zynthian adds another chain (another channel), but changes first chain audio to now choosen station. Now you have 2 chains, but another is just "dummy" with correct station name, but silent. You can add third etc chain, choosen station always plays on first, only name added. 

![inet_radio_mixer](https://github.com/user-attachments/assets/7ecb84d1-8850-4938-9760-db7a0f208b77)

**Comment by riban-bw** [comment]
This is fixed by zynthian/zynthian-ui@f43f2935947c161e2e3677ba3e893ec918807082.

This makes Internet Radio a single instance engine which I think is acceptable. It feels like an odd corner-case where multiple Internet radio streams are required.

You can use normal preset selection mechanisms to change channel. It does take a few seconds to sync to the new stream so there isn't cross-fading between streams.
