### ISSUE TITLE
Add ZS3 name to Mixer header, along Snapshot name

### ISSUE THREAD

**Issue by Potajito** [zynthian/zynthian-issue-tracking#1220]
**Is your feature request related to a problem? Please describe.**
Current GUI lacks some info (selected ZS3 name) that could be useful, and it's very easy to get lost on which ZS3 patch you are using, specially when live playing, as reading the vertical faders is not super easy. 

**Describe the solution you'd like**
It would be useful to have the selected ZS3 name added to the Mixer header, so the header would look something like:
Mixer: Snapshot name - ZS3 name
Also, as suggested at https://discourse.zynthian.org/t/would-it-be-possible-to-have-zs3-name-in-the-mixer-header/10226
"the ZS3 name could be displayed only if it has been manually set by the user, i.e. not ZS3-1 or indeed the default snapshot zero-state, ZS3-0."

**Additional context**
Also, given that screen real state is limited, maybe is not a bad idea to drop the "Mixer:" Part of the string, as this is one of the most obvious screens. Anyway this is pretty minor, as even if screen space is limited, it should be plenty to show everything.

**Comment by riban-bw** [comment]
@Potajito has created a ["dirty hack"](https://github.com/Potajito/zynthian-ui) but I think we should improve zs3 handling which would make this much easier to implement.

Currently we save the current state to zs3-0 during snapshot save and recall zs3-0 during snapshot load. We should add a value to the zs3 state model that indicates which zs3 is currently (last) loaded so that it can be recalled next time. This could then be used to get the title of the zs3 from state manager. (There is already a function to do this.) We could also compare zs3-0 with the most recently loaded zs3 and indicate if it is dirty, e.g. add '*' to the name.

**Comment by riban-bw** [comment]
Implemented in vangelis (testing) branch.
