### ISSUE TITLE
Bug: The 'are you sure' passes by too fast when overwriting an LV2 preset

### ISSUE THREAD

**Issue by polluxsynth** [zynthian/zynthian-issue-tracking#1262]
**Describe the bug**
When saving an LV2 preset which already exists, i.e. overwriting an existing preset, after pressing Enter in the display, a question shows up asking if it's ok to overwrite the preset. However, it seems that the Enter press (which is in the same region on the screen as the YES response to the overwrite question) also gets interpreted as a YES press, so in practice, the 'Are you sure' screen is shown for a fraction of a second before the preset is overwritten.

**To Reproduce**
1. Bring up an LV2 plugin such as MiMi-d
2. Save a preset to a writable bank (i.e. bold click Select, select the plugin in the chain, click Select, select Save Preset, enter the name, click Enter)
3. Overwrite the preset using the same procedure (need to back out the ' COPY' suffix to the preset so that the name is unchanged from the previously saved preset).
4. Note how the 'Are you sure' screen is barely visible as it flashes by, and the preset is instead overwritten directly.

**Expected behavior**
The 'Are you sure' question should appear with NO and YES fields, and wait for a distinct screen press.

-   SD-image: 2024-09-23-zynthianos-bookworm-aarch64-oram-2409.img (plus updates)

-  Hardware Config (Zynthian v4 - in the webconf, Kit is set to v4):
    Raspberry Pi 4 Model B Rev 1.4
    Audio: HifiBerry DAC+ ADC PRO
    Display: ZynScreen 3.5 (v1)
    Wiring: MCP23017_ZynScreen
    I2C: MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, MCP4728@0x61

-   Software Version
    zyncoder: oram (71de6d2)
    zynthian-ui: oram (bbc7246)
    zynthian-sys: oram (a717e49)
    zynthian-data: oram (ddfa009)
    zynthian-webconf: oram (b530397)

**Comment by riban-bw** [comment]
There is a key pressed timer to allow DELETE to key to clear the field when held. There should also be an auto repeat (although that doesn't seem to work. These resulted in the code triggering keys on press, not release. I have changed the code so that the ENTER and CANCEL keys trigger on release. I left the others because they should work with auto repeat (if anyone reports it not working as a bug...).

Fixed in vangelis (testing). Ready for deploy in next stable (oram) point release.
