### ISSUE TITLE
Put built-in patches etc. first.

### ISSUE THREAD

**Issue by 1st-BrainStormer** [zynthian/zynthian-issue-tracking#140]
It would be nice if the built-in stuff would show at the top of a list.
For example in fluidsynth when looking at the sound font list should start with:

FluidR3 GM
FluidR3 GS
TimGM6mb

And everything in zynthian-my-*  Would show up below the built-in's

**Comment by jofemodo** [comment]
It's implemented like that on purpose: "User presets are shown first"

if you think it should be changed, open a thread in the forum and let's see what other user think about ... 

I don't have any problem on change this behaviour if it's what users really want ;-)

**Comment by 1st-BrainStormer** [comment]
The other option is to allow wrap-around.  So I could go up into the built-ins or down through the user presets. Or a setting in web-config to set desired order.

I have uploaded my favorites into the built-ins folder since it is shorter which is why I suggested this.
the user preset folder has several  hundred patches so takes a bit of scrolling to get to the bottom.

**Comment by sehrgut** [comment]
Maybe an alternative options would be to implement bank directories for SF2? Currently the SF2 directory has a single level. I would love or it to work like the SFZ directory, with the ability to have "banks" by directory. If it were implemented the same way, the external banks would be prefixed "Ex" as well, which would answer the original request by making it simpler to find built-ins.

**Comment by jofemodo** [comment]
The problem is that many SF2 already work as banks, having several instruments inside. It's what zynthian assumes.
Perhaps we should re-think the too-rigid bank/preset paradigm that zynthian implements from the first days, but it has lot of implications, starting by the fact that is the MIDI's paradigm too. Anyway, i will give it a try ... 

BTW, regarding to this issue, i'm thinking that "Favorites" sould solve the problem.
 
Thanks,
