### ISSUE TITLE
Snapshot: No upload button when all banks are removed

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-issue-tracking#278]
**Describe the bug**
When removing all Banks (including Bank 0) no upload button is shown.

**To Reproduce**
1. Go to Libraries/Snapshot
2. Remove _all_ banks
3. Again, go to Libraries/Snapshot
4. Only the "New Bank" selection box is shown - no way to upload a bank.

**Expected behavior**
There should be a way for uploading the banks without any bank installed.

**Screenshots**
-

**Setup:**
 - 2020-09-05-zynthianos-buster-lite-armhf-1.0.0.img
 - 
```
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017
```
 -
```
zyncoder: master (d706b12)
zynthian-ui: master (187845e)
zynthian-sys: master (a06533e)
zynthian-data: master (74ceb35)
zynthian-webconf: master (d25055c)
```
**Additional context**
Currently uploading of a bank (regardless if there is a bank or not) does not work for me. Will ask inside the forum and perhaps open an additional issue for this.

**Comment by jofemodo** [comment]
Hi @dcoredump !

AFAIK, uploading banks has never been implemented on snapshots. You can only upload/download snaphots once a time.Snapshots MUST be inside a bank, so If you delete all banks, you can not upload snapshots until you create a bank.

Anyway, i think having implemented bank uploading/downloading would be nice and it's almost trivial because it's already implemented for presets. So, i would change the title of this issue ... ;-)

**Comment by jofemodo** [comment]
I will close this. Uploading full snapshot bundle-banks implies complex sanitizing and i don't see a clear use-case.
