### ISSUE TITLE
ZS3 enable or disable

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-issue-tracking#370]
It would be good to have the possibility to edit
wich channel is part of the ZS3 process and wich not.

When I'm using the ZynSeq i use the channels 9-13 for the backing tracks.
And it would be fine to change the sounds I play by myself on the keyboard.

Maybe that i didn't find the right workflow.

**Comment by jofemodo** [comment]
In multi-timbrial mode (when you are using the sequencer you should be in multi-timbral mode), ZS3 works in a different way than when you are in "Stage Mode". In multi timbral mode you can use ZS3 for changing the preset on the channel (layer) your keyboard is set, but you can't change to a different layer because on multi-timbral mode, each layer is bond to its MIDI channel.

Regards,
