### ISSUE TITLE
Issues with audio recording

### ISSUE THREAD

**Issue by multim0** [zynthian/zynthian-issue-tracking#444]
In all my audio recordings on USB flash drive that are longer than 60 seconds, after about that time audio is distorted till the end of recording. Sometimes recording is also called #NO-jack_capture.wav instead of selected layer. This happens both for Synth Engines and Audio FX layers recording.
I haven’t noticed anything problematic during recording, as sound from audio outputs (and Rpi headphone outputs) was fine all the time. I discovered this during recording playback on Zynthian and my phone.
Some things that may be related:
1. Recording is not available instantly after I click “stop recording”, and time indicator stucks on 0:00 for even few minutes. Is it normal? Is there some postprocessing going on then?
2. On first boot of Zynthian stable image red “ERROR” text appears on boot splash. On later boots starting screen is fine.

When I looked in UI loga there was nothing more than start/stop recording even in debug logs.
How can I investigate this more: is there any way to enable writing logs on USB by default, as I do not want to flood my sdcard with them?

To Reproduce:
Steps to reproduce the behavior on my device:
1. Go to 'Audio Recorder' 
2. Click on 'Start Recording'
3. Play some audio either on audio fx or synth engine channel. 
4. Stop recording after about 1 minute. 
5. Audio will be distorted in the end of the recording. 

Expected behavior:
Recording should be fine :D

Setup:
 - latest stable image (early April) from wiki
 - Kit v4.3 8GB
 - stable

**Comment by jofemodo** [comment]
Could you check if this problem is present when recording to the internal SD card? Could you try with other pendrive?

**Comment by multim0** [comment]
Like I've written here: https://discourse.zynthian.org/t/issues-with-audio-recording/5778/10?u=multim
It seems that this problem is connected with low write speed of standard USB 2.0 (and some slower 3.0) flash drives. 
For internal SD card and faster USB 3+ flash drives problem does not occur. 

This might be addressed as verbose error log/message from jack_capture or another recording metod should be used for slower drives.

**Comment by riban-bw** [comment]
I have done some investigation and see that some USB attached storage has low write speeds. 48000 samples/sec 32-bit audio has a bitrate of 1536000 per audio channel. This gives us 384000 bytes per second for a stereo stream. The storage must be capable of reading and writing faster than this to allow audio to be recorded and replayed. For short recordings this is less of an issue because the audio will be stored in memory buffers and written to disk periodically so the sustained write speed can be lower but as the file grows, the buffers will be depleted and we hear distortion as data is corrupted.

We could test each USB storage device when it is connected, e.g.
```
sync; time `dd if=/dev/zero of=/media/root/BOOTMEDIAW1/test bs=1K count=375; sync`
```

This would give us the time to write 1s of 48000, 32-bit stereo audio. Note that we time between `sync` to measure the actual data write time rather than the time reported by `dd` which seems to ignore this! We need to use a fairly large file to write to get a realistic report of the sustained write speed. Small files (like 1s long) seem to write very quickly. Also the results vary widely so we should take many readings although we might be able to get sufficient indication with a single short write.

I did a few more tests and the results for 1s, 10s & 100s are fairly linear so we could probably get a good indication of the performance of attached storage with a single short test although the first write after a period of inactivity seems to take longer.

We could perform such a test when a USB storage device is inserted for the first time. We could write the result to a database indexed by the USB UID so that we avoid writing to devices excessively. We can get the UUID with the `blkid` command.

A python script like this might work:
```
###############################
from os import system
from time import monotonic
import jack
import subprocess

def get_write_speed(path, samplerate=48000, dur=10):
    blocks = samplerate * 8 * dur // 1024
    system('sync')
    a = monotonic()
    system(f"dd if=/dev/zero of={path}/.zyntest bs=1k count={blocks} > /dev/nul 2>&1")
    system('sync')
    b = monotonic()
    system(f"rm {path}/.zyntest")
    return (b - a) / dur


def get_uuid(path):
    result = subprocess.run(['blkid', path], stdout=subprocess.PIPE).stdout.decode('utf-8').split()
    for i in result:
        if i.startswith("UUID="):
            return i[6:-1]

def get_mount(path):
    result = subprocess.run(['mount'], stdout=subprocess.PIPE).stdout.decode('utf-8').split("\n")
    for i in result:
        if i.split()[0] == path:
            return i.split()[2]

def get_speed_pair(path, samplerate):
    mount = get_mount(path)
    uuid = get_uuid(path)
    speed = get_write_speed(mount, samplerate, 10)
    return (uuid, speed)

client = jack.Client("zyn_speed_test")
samplerate = client.samplerate
get_speed_pair("/dev/sda", samplerate)
```

I think we can get a fair indication from a 1s test because the difference between slow and fast storage is evident even with such short tests. Longer tests may be too slow to run on slower media. We could do a short test then longer ones if the disk responds quickly. My Sandisk can record audio and returns approx. 0.1 from this test script so we may want to warn if the result is approaching 1.0 (although that would be worrying so maybe 0.5 is a better threshold).

**Comment by jofemodo** [comment]
I just tried jack_capture with this paramters:

cmd = ["/usr/local/bin/jack_capture", "--daemon", "--bitdepth", "16", "--bufsize", "30", "--maxbufsize", "120"]

And the issue vanishes when recording stereo from main output. I just recorded a 4 min track to internal SD without a "pop".

**Comment by riban-bw** [comment]
Indeed, limiting data bandwidth will help. We could implement a combination of detection and throttling. If we detect the storage to support fast transfer then we could use higher bandwidth (48000, 32-bit, wav) and reduce the bandwidth for lesser performant storage, e.g. reduce word length to 24 or 16, reduce samplerate, use different codecs (flac, ogg, etc.). The latter may not be desirable as we ideally want the file to be fully compatible with other systems but this could be resolved with webconf transcoding. This could be done automagically and / or via user configuration.

**Comment by riban-bw** [comment]
I have a script working that tests attached storage write speed when attached to USB and writes to a file (only if not already in the file). This is triggered by devmon. We can then use this file within zynthian_gui to make informed decision on whether and how to throttle data write bandwidth.

The addition to `/etc/conf.d/devmon` is:

```
ARGS="--exec-on-drive '/root/on_drive_mount.py %f'"
```

Obviously we could put the script anywhere. The script  is modified from what I posted previously but I have just realised it has a flaw in that failure to write the test file does is not detected. I will fix that.

**Comment by jofemodo** [comment]
It's been greately improved! Could we close this?

**Comment by multim0** [comment]
I've retested only on stable, I could flash oram and retest it once again until end of this week.

**Comment by multim0** [comment]
On stable there were some minor glitches, but still much better than when I've reported this issue.
On oram for the same slow USB flash drive recording quality is flawless.
Closing.
