### ISSUE TITLE
Please enable vnc:5900 via menu for the main zynthian screen (as well as vnc:5901 for instruments)

### ISSUE THREAD

**Issue by julesdg6** [zynthian/zynthian-issue-tracking#447]
Before VNC was made available in webconf for instruments, i used to use it to control my zynthian. Can it also be added to the menus?

**Comment by riban-bw** [comment]
A good solution to this might be:

- Install x11vnc
- Add a service to start `x11vnc -display :0 -N -forever`

This starts the mirroring of the main display to vnc port 5900, restarting if the xserver restarts, e.g. zyngui is restarted. I have tested this with x11vnc from Buster and it seems to work quite well. We may need to add `-inetd`, `-q` and `shared` to indicate it is started as a daemon, it should not log output and to allow multiple connections.

We also need to add another noVNC instance with the `--listen` option so that we can define the noVNC port to monitor.

Also add the feature to webconf and UI code.

This is failry trivial and I may be able to have a bah in the next few days. It may be advantageous to use a single vnc server solution, i.e. lose tigervnc but that would be for another ticket...

**Comment by riban-bw** [comment]
I have created branches on zynthian-ui, zynthian-sys and zynthian-webconf and implemented vnc (and novnc) access for main and secondary screens with password protection. I haven't figured out how best to remove old service files (@jofemodo ?).

Would someone take a look and see if this works and is acceptable to merge with testing? I tested on a virgin machine but three is always the chance I missed something.

**Comment by riban-bw** [comment]
I have submitted pull requests for each branch. Please review. I will make changes as required.

**Comment by jofemodo** [comment]
Hi @riban!

I just read the changes and it seems OK. Tomorrow i will test it and, hopefully, merge it.

Goog work! ;-)

**Comment by jofemodo** [comment]
OK! Tested and merged! BTW, i simplified a little bit the VNC options labels on the menu. Also, i moved all remote interface options to "interface" menu.

**Comment by riban-bw** [comment]
Not working on my official V4.1 running Testing. After a reboot I don't see any access to noVNC from webconf.
