### ISSUE TITLE
MIDI player doesn't work fine

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-issue-tracking#461]
**Describe the bug**
When playing some MID files, note-off events are not managed correctly and lots of notes remain on.

**To Reproduce**
Load the snapshot and play the MID file included on this zipfile:

[House In RTP.zip](https://github.com/zynthian/zynthian-issue-tracking/files/6529359/House.In.RTP.zip)

You will ear the beginning of a theme that progressively get a total mess.

**Expected behavior**
Ear a nice theme from @JTunes

**Setup:**
 - Latest Stable SD image
 - Kit v4.2

**Comment by jofemodo** [comment]
What do you think of restoring the older MIDI player until problems with the new one get solved?

**Comment by riban-bw** [comment]
That is a bit tricky for to the integration between modules. I will take a look at this issues as soon as I can.

**Comment by riban-bw** [comment]
Actually that was not the problem. Note-off events are converted to note-off events with zero velocity. (This helps with tracking events to reduce risk of stuck notes when stopping playback and can help with data flow when running status is used.) This conversion ignored channel hence all note-off events were sent on channel 1 (0). Fixed in dev branch bug/461_smf_stuck_notes commit f87e42173b208078fd26f24e020d78c02607924e. PR imminent.

**Comment by jofemodo** [comment]
Merged on testing.
