### ISSUE TITLE
Add Audio Recorder output as a source in zynmixer

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#553]
**Is your feature request related to a problem? Please describe.**
Make the audio recorder playback available as a source in the zynmixer

**Comment by riban-bw** [comment]
It may also be advantageous to allow it to be sent directly to main output, bypassing mixer which may be useful when providing incidental interval music.

**Comment by wyleu** [comment]
agreed
Would that be another master bank on the right hand side of the mixer?

**Comment by riban-bw** [comment]
This needs some consideration. Maybe the user needs to manually add the audio player as a layer to make it present in the mixer. If not added as a layer it performs as now, i.e. appears, routes to main output then disappears at end of playback without a mixer fader. If the user adds audio player as a layer then it appears in the mixer as a normal channel strip. Maybe we don't implement direct output but instead use the solo feature. This means the player would still go through the (yet to be implemented) main output effects chain (unless we do something interesting there to allow bypass).

**Comment by wyleu** [comment]
I mentioned in my write up of the wedding how the existing mechanism leads to issues. The lack of a volume control when not playing is difficult if you want to fade up a particular channel or even just ride the fader.

Overall why couldn't we make the audio recorder an engine like everything else? It's suffering under it's own success in that it has demonstrated itself to be a useful tool in the swiss army knife approach but it is probably at a stage where we could consider it in light of the wider view the zynmixer takes.

For instance I would like to run two ( or more ) audio tracks . A walkout piece of music AND church bells. 
IF we invest too much effort into the existing audio recorder we might loose the opportunity for wider implementation that a correct placing of it' functionality could provide.

**Comment by riban-bw** [comment]
I agree (and there may even be evidence of it). The audio recorder and player would benefit from being modified to provide required functionality. I suggest we split them so that the recorder is available globally and quickly to capture audio recordings. This could include features such as continuous record (capture stuff before you press record button) and level detection. The player could be an engine which can have features such as playlists. An engine could then simply be added as a layer and appear on the mixer.

So do we change this request to one that asks for audio player to be an engine with detail of the requirements? The control screen could show the list of available recordings and allow them to be ordered and tagged for playback.

**Comment by wyleu** [comment]
Agreed. I have the toggle record function available as my first membrane switch so I already treat it as a separate component.

The control screen could show the list of available recordings and allow them to be ordered and tagged for playback.

**Comment by riban-bw** [comment]
I am closing this issue because the current implementation seems okay. 

The default audio player is mainly for reviewing last recording. To uses an audio player for general use, add zynsampler to a chain for full control.
