### ISSUE TITLE
Screen blanker

### ISSUE THREAD

**Issue by 1st-BrainStormer** [zynthian/zynthian-issue-tracking#57]
Add a setting to turn on and off a screen blanker with optional timed trigger.
When screen is blanked, hitting any of the push knobs would wake it up.
These are the commands for this:

# Turn off backlight
echo 1 | sudo tee /sys/class/backlight/*/bl_power

# Turn on backlight
echo 0 | sudo tee /sys/class/backlight/*/bl_power

**Comment by riban-bw** [comment]
This could be implemented and may be useful but please @1st-BrainStormer describe the reason you want this. It will be easier to implement the feature with the context in mind. I can see that it may be useful for the screen to blank for various reasons but these may differ between users, e.g. it may want to go dark overnight to allow a unit to be in a bedroom or it may be useful to avoid glare on stage or in videos, etc. The user may want a screensaver to kick in after a period of inactivity (is that user interaction, playback, etc. ?) or be manually triggered.

We would need to record the state so that the first user activity did not trigger an operation, i.e. pressing a button should only wake and not trigger the action of that buttton.

**Comment by riban-bw** [comment]
Power save is now implemented.
