### ISSUE TITLE
Cannot load Pianoteq presets in Webconf Library

### ISSUE THREAD

**Issue by VaikoHansson** [zynthian/zynthian-issue-tracking#573]
When trying to add Pianoteq presets in Webconf library I get a white screen. Other plugins show the folder tree and upload form correctly.

Zynthian v 4.4
Pianoteq 7.4 Standard

[pianoteq-preset.zip](https://github.com/zynthian/zynthian-issue-tracking/files/7557622/pianoteq-preset.zip)
<img width="1680" alt="Screenshot 2021-11-17 at 18 43 45" src="https://user-images.githubusercontent.com/438531/142272263-e0029dcf-702c-4c8a-ac26-9044a712229e.png">

**Comment by mheidt** [comment]
@jofemodo 
Please take a look.
I had to set the readonly flag of the My Preset bank to true, because the Rename/Delete Preset panel is only shown, when bank AND preset are not readonly.
The My Presets bank can't be deleted nevertheless, because zynapi_rename_bank doesn't exit.
The icon is the normal bank-icon though. I hope this is okay.

**Comment by jofemodo** [comment]
OK! Tested and merged ;-)
Thanks a lot, @mheidt !
