### ISSUE TITLE
Add Bluetooth MIDI  (BLEMIDI) support

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#586]
**Is your feature request related to a problem? Please describe.**
Althou I can connect to bluetooth devices using aconnect and sucsessfully dumping into aseqdump, the alsa bluetooth MIDI ports are not visible to the zynthian infrastructure. They dont appear in amidi -l

**Comment by wyleu** [comment]
The required behavior can be implemented by 
1/ extracting ALSA device ID for aconnect -l
2/ connecting to  client 14: 'Midi Through'

root@zynthian-1820:/zynthian# aconnect -l
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
        Connecting To: 128:0
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
        Connecting To: 128:0[real:0]
        Connected From: 128:0
client 16: 'f_midi' [type=kernel,card=0]
    0 'f_midi          '
client 24: 'MPKmini2' [type=kernel,card=2]
    0 'MPKmini2 MIDI 1 '
client 28: 'UMC1820' [type=kernel,card=3]
    0 'UMC1820 MIDI 1  '
root@zynthian-1820:/zynthian#

**Comment by riban-bw** [comment]
There has been a lot of work done to add BLE MIDI to Zynthian but the migration to 64-bit / Debian 12 (Bookworm) seems to have broken BLE MIDI. I will fix it...

**Comment by riban-bw** [comment]
I have pushed some fixes for BLE MIDI.

BLE MIDI devices are not recognised by jack2 (`-X raw`). I have re-enabled hardware port forwarding of a2jmidid. This causes errors in the log for hadware ports that have already been grabbed by jack but it seems to work as required. The BLE MIDI device detection code is repeated for the a2j devices. We could / should probably remove the old capture code.

I have removed the override to bluetoothd service from zynthian-sys because it was using the wrong path to the command and the eperimental params are no longer required but this won't fix it for users who have already run an update, i.e. this does not remove the previously installed (now bad) file in `/etc/systemd/system/bluetooth.service.d/`. I would prefer to not have a _removal_ script for something that should not be put there in the first place but maybe we will need to add that???

**Comment by riban-bw** [comment]
Ah! This will fail occasionally when hot plugging USB devices. a2jmidid may grab the device instead of jackd. This is a pain. It was working but the BLE MIDI implementation may have changed in Bookworm / later kernel. More investigation needed...

**Comment by riban-bw** [comment]
Actually - even the previous method of linking BLE device to ALSA or JACK port was flawed. I am yet to find a link between the two which means that devices with the same name are indistiguishable. I continue to investigate /proc and /sys...

**Comment by riban-bw** [comment]
I have recompiled bluetoothd with a modification to include the BLE address in the device name which could help. bluetoothd creates alsa userspace sequencer MIDI ports. These are not recognised by `jack -X raw` or by `a2jmidid` (without `-e` parameter). As previously described, adding `-e` to `a2jmidid` breaks USB hot plug.

We could add instances of `a2jmidi_bridge` for each BLE MIDI port but this is more overhead to manage. I will investigate implementing direct jack integration with bluetoothd. This could add the BLE MIDI ports as jack ports instead of alsa ports which resolves most of the issues, leaving a little python coding to do in zynautoconnect. It would also remove the extra hop between alsa and jack (via a2jmidid) which might reduce latency / jitter. Such an enhancement may not be desired upstream so we may need to maintain a fork of bluetoothd (which is part of bluez). This may be okay, depending on other userspace bluetooth integration we may want.

For now I want a pragmatic solution. We can revisit if necessary. I will look at the jack integration...

[Edit] I will first investigate whether we can use virtual raw alsa ports. This might allow `jack -X raw` to recognise the port, simplifying the code changes and increasing the chance of upstream adoption.

**Comment by riban-bw** [comment]
I have patched bluez to provide Jack2 MIDI support in bluetoothd. This allows us to run the bluetoothd service and present BLE MIDI devices as ports on a native jack2 client. This works well but there are some other bluetooth oddities that need to be resolved so this isn't fully working yet.

I suggest that we get the core bluetooth functionality into Oram but do not block Oram release for refinements that can be done later, i.e. Oram will have "experimental Bluetooth support".

**Comment by riban-bw** [comment]
We need to fork bluez so that we can track our changes.

@jofemodo please fork `https://github.com/bluez/bluez.git` and provide me access to the repro so that I can apply my patches.

**Comment by riban-bw** [comment]
Just adding a note here of how to compile bluez.

```
git clone git@github.com:zynthian/bluez.git
cd bluez
autoreconf -i
./configure --enable-midi --disable-tools
make
make install
```

**Comment by riban-bw** [comment]
I have created a branch `jack_midi` on the zynthian fork of bluez and commited the changes that add a new compile option: `--enable-jackmidi`. With JACK MIDI enabled, each BLE MIDI device creates an input and output MIDI port on a single JACK client called "BLE_MIDI".

Zynthian code has already been committed to Oram branch to support this. We now need to uninstall `bluez` (if it is installed in the default image) and to decide how to install the following executeables from the patched bluez:

- bluetoothd
- bluetoothctl

Do we create our own deb package or just install the two files from somewhere? Is there a suitable place to store our own custom executables?

**Comment by riban-bw** [comment]
Yay! Finally, I think this is done. I am going to close this ticket. @wyleu please test on Oram and let us know of any issues.
