### ISSUE TITLE
Ability to manage presets from UI

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#614]
**Is your feature request related to a problem? Please describe.**
It would be advantageous to be able to manage presets directly from the Zynthian UI.

**Describe the solution you'd like**
- Select existing presets (already implemented)
- Add new preset from current configuration
- Rename preset
- Delete preset
- Overwrite existing preset
- Toggle preset in favourites (already implemented)

**Describe alternatives you've considered**
Some of this is possible from VNC but not for all engines.

**Additional context**
A [Pull Request](https://github.com/zynthian/jalv/pull/1) has been submitted modification has been done to allow manipultation of LV2. This may need enhancing to allow more features like delete, rename, etc.

I suggest using the bold SELECT action from the preset list (currently assigned to toggle favourite) to open a context menu offering the list of options described above. (Short SELECT should select preset.) The preset should be added to the same bank that is selected. There may need to be similar functionality for bank management. We may need to decide if we want to protect built-in / default presets or allow manipulation of all. Maybe an ability to overwrite existing presets with abilty to restore default (although this adds complexity including how to restore deleted presets but it would probably be the most complete and intuitive method).

**Comment by wyleu** [comment]
How would the naming of new instances of a specific preset be implemented?
Is a chain of origin to be maintained? Do we have a parent file field in the description? Could this be implemented as created and maintained so the original preset from which it is derived is identified and the last modification is also maintained, allowing development graphs to be extracted.

**Comment by riban-bw** [comment]
I am unclear of the benefit of adding ancestry tracking. The ability to restore deleted or modified presets seems useful so that users can clear unused / unwanted presets with the ability to reinstate (factory defaults). I don't think ancestry info warrants the additional complexity.

[Edit] How about we make the factory defaults available online like a website so that users can reinstall them? That way we don't have to implement a mechanism within Zynthian to store user / factory presets separately with the complexity of hiding unwanted factory presets.

**Comment by jofemodo** [comment]
This is duplicated:

https://github.com/zynthian/zynthian-ui/issues/287

;-)

**Comment by jofemodo** [comment]
Regarding the new preset options menu to be implemented, i propose to have this simple options:

+ [  ] Favorite 
+ Save
+ Rename => User-saved presets only
+ Restore / Delete  => User-saved presets only

The last entry "Restore/Delete" is a little tricky, but i hope you like the idea. When you create a preset in the "zynthian-my-data/presets/lv2" directory, it will replace (without deleting!) the "factory" preset if there is a preset with the same name in the same bank. This is the normal behaviour of LV2, that works in a similar way to the well-known "search path" mechanism. So, why not to take profit from this mechanism? ;-)

+ If the user doesn't change the name, the saved preset will override the factory preset, and the menu would show "restore" instead of "delete". This is the most tricky part, because we have to detect the override and i'm not sure the lilv library will help us with this. Anyway, in the worst-case, it's not too complex to implement.

+ If the user choose a new name, the saved preset wont override any factory preset and the menu would show "delete" instead of "restore". Easy.

Note that the delete/restore entry will be shown only for user-saved presets, what could be confusing. Perhaps we could flag presets as factory/user/override in a more explicit way, so the user could better understand why some menu options are not always available.

In a similar way, the menu would show the "rename" entry for user-saved presets only, as it's not convenient to rename factory presets.

Anyway, this is only a first approach. Let's implement something minimal but functional, and let's see what is the next step, OK?

Best Regards,

**Comment by riban-bw** [comment]
I think this issue is better described and considered than #287 so maybe we should continue our progress here and close #287? The main points made in #287 are:

- It may be challenging to implement a consistent mechanism across all engine types - this is a challenge to be investigated and hopefully solved
- Extending or abstracting the snapshot mechanism or principle or workflow may be advantageous - I don't think this would prove benficial. The work being done here shows a good path to preset management.

Regarding the last comment by @jofemodo, I like the concept but think we should also allow the opposite, i.e. the ability to hide factory presets. Sometimes a user (like me) is overwhelmed with the quantity of presets and finds it hard to navigate them. I know we have the favourites option but that doesn't resolve the issue of having to navigate many (sometimes hundreds) of presets. Maybe a mechanism to delete / hide default presets and an option to show all to allow restoring them.

The four options that @jofemodo suggests align with the six I suggested. One of mine related to recalling presets which is implemented outside the context menu. Another related to Save As which can be combined with Save by showing the onscreen keyboard and if the user changes the name then it does a Save As but if the user just hits ENTER then it saves over the currently selected preset. That is neat and fairly simple workflow to understand and learn. I will create a branch of zynthian-ui and implement the context menu in this format and work on the core implementation. (Menu is easy...)

**Comment by polluxsynth** [comment]
A few comments from the sidelines: I'm thinking of how preset management works in a classic synthesizer, with no undo option, but often an "are you sure" step prior to overwriting existing presets. Many synths back in the day had a few banks of "ROM" presets which could not be overwritten, plus a few user banks. I think it would be fine not to allow overwriting of the factory presets in Zynthian and only allow writing to a user's bank. Being able to shadow factory presets with a user's version is a bit over the top at this stage IMHO.

I agree with @jofemodo that we should aim for something simple to start with and add refinements later. So the primary, and easiest-to-access function should be to write presets to the user's bank. Things like delete, rename, etc could be in a separate 'administration' menu, or even in the webconf.

Alternatively, the save/load paradigms from the snapshot menu could be used, which the users are already familiar with, but on the other hand, when it comes to presets, loading them is simpler than with snapshots as you only have to select the name and not enter a second menu and click load, so perhaps this is not a good route.

The fact that we're considering lv2 support only so far I think is fine for now, it's a great step forward. For Zynaddsubfx for instance, since it's not possible to edit the actual patches on the Zynthian, there's no real need to save them either, as once you've got a UI up to do the editing you can use it to save the patches as well.

**Comment by riban-bw** [comment]
Thannks @polluxsynth for that useful comment.

I am implementing a confirmation dialog for destructive actions like overwritting an existing preset as is the norm within Zynthian UI.

You have a good point about consistency. I just looked at snapshot management and the behaviour differs. @jofemodo we should decide which is best and make it consistent. I like the ability to select the preset with a single press so maybe we change snapshot to match, i.e. move the "Load" option from the menu to be the default "short SELECT" action and access the context menu via bold SELECT.

I agree that we could (at least for starters) implement user managed presets and simply leave the factory presets as read-only. This is an established concept so quite intuitive. If we want to add a layer of complexity to the code later then we can do so. (I do like the idea of a user layer over the factory defaults - it is kinda cool but baby steps...)

I don't think preset management should be in admin menu nor only accessibe via webconf (which is mostly already implemented). Many users want to be able to manage the preset right at the point they are manipulating it so we should continue with the context menu (which I have already implemented in the dev branch). It can have just the implemented features, e.g. if an engine does not support renaming then the option can be omitted from the menu.

I am considering support across all engines, not just LV2 but I am using LV2 as the first test because I need to start somewhere and this is the majority of engines. You certainly can edit some parameters of Zynaddsubfx within the UI and we may want to expand that (or just use the LV2 version) in the future. Other engines have more or less control, e.g. all params of setBfree are accessible from UI.

I have created the dev branch with the context menu implemented. Toggle preset is implemented as suggested by @jofemodo. Other options don't do much yet.

**Comment by jofemodo** [comment]
+ I think the preset override feature *MUST* be implemented, because it's easier to implement than to not implement. I mean the "search path" mechanism is imposed by LV2. When you save on the user's preset directory, you will override a factory preset if using the same name and bank, so you are forced to detect the collision if you want to avoid it, and the effort to do so it's the same (in fact, i think it's more complex) that the effort for implementing the override mechanism with the "restore/delete" entry.

+ Regarding the "short-select" for loading preset/snapshots, it's OK. but it should be considered a destructive action, so you should be asked to confirm if something has been changed from the last snapshot/preset load. Currently we have not a "dirty flag" mechanism for snapshots nor presets (obviously!), so we should implement this if we want to use short-select for loading.

+ Regarding other standalone engines, i think it has no sense to save presets in their native format and ZS3 would be more useful in these cases. More detailed:

    + ZynAddSubFX => Although saving presets is almost trivial using the ZynAddSubFX OSC interface, i think it's not useful at all. We don't expose the synth engine parameters and only a subset of "control" parameters are shown. I mean you can't really create new presets or modify existing ones from zynthian GUI. 

   + Soundfonts (FluidSynth, Sfizz, Linuxsampler)=> Obiously, you can't create new sounfonts or modify existing ones. You  can only adjust a few control parameters like volume & balance.

   + Pianoteq => In it's current state, you  can only adjust a few control parameters like volume & balance. When we integrate all the parameters, what is now possible, we should consider to save presets in its native format.

   + setBfree => Only 127 presets can be defined, what is quite limiting. I would consider to totally override the setBfree native preset implementation and replace it by a zynthianic bank/preset mechanism based on ZS3.

   + Aeolus => From my POV, this is the only standalone engine that (currently!) we should consider for implementing "save preset" using its native format. It implements a MIDI-like bank/preset mechanism, what it's fine. I already implemented the parser for the preset's binary format, so only the write part remains to be implemented. 

Anyway, i would concentrate on LV2 and we would take over this on a next iteration, OK?

Regards,

**Comment by jofemodo** [comment]
@riban-bw , please, have you read my comments on the jalv's PR?

https://github.com/zynthian/jalv/pull/1

Thanks!

**Comment by riban-bw** [comment]
Regarding RP - I will revisit once I have a better understanding of the requirements from our use-cases. I can see that the work I did there is not necessarily optimal nor aligned with the _interesting_ way that Zynthian interfaces with LV2, i.e. there is the persistent storage of the presets in ttl files, the optimised _cache_ version of this stored in json file and the in-memory current state of presets which all need to be synchronised. I am working through that at the moment.

Regarding dirty flag - we need to decide how dirty something needs to be before it is flagged, e.g. an adjustment of a volume may or may not be desirable to indicate dirty - I will take a look at that. But in principle I agree that overwriting should be confirmed.

A straw poll in this week's zynth club showed overwhelming preference for traditional method of user preset handling where factory presets remain read-only and users can add / delete / modify presets within user banks. I proposed the ideas discussed here and argued their merit but everyone thought it a complexity that offered little or no benefit, was confusing and may detract from operational workflows. I think we should plan for the best workflow and deal with implementation complexity as we meet it rather than design workflow based on ease of implementation.

**Comment by jofemodo** [comment]
I think your work on Jalv is in the right direction, although i would avoid the "-P" flag, using the CWD, as already used on native GUI's "Save Preset" menu option.

Regarding the Zynthian's LV2 preset cache, we should re-generate & reload the plugin's preset cache after saving/renaming/deleting presets. Not difficult at all because it's already implemented on _zynthian_lv2.py_

Regarding dirty flag, i would implement the mechanism in a clean way and leave the fine-tuning for later.

I agree with zynthclub's view about simplicity and clearity, so let's have this minimal menu:

+ [ ] Favorite
Save as ...
Move to Bank  => Only for user presets
Rename => Only for user presets
Delete => Only for user presets

Regards!

**Comment by riban-bw** [comment]
I don't like having to work in cwd but I can take out that option now that I understand how Zynthian manages it's user preset path.

I will ensure jalv / lilv / Zynthian have the appropriate functions to allow each option to work on the various data sets:

- Memory resident LV2 state
- Persistent LV2 data (ttl files)
- Memory resident cache
- Persistent cache (JSON files)
Some is already implemented but not all

**Comment by riban-bw** [comment]
This has proven to be more challenging, partly due to some partially implemented, related functions and inconsistency of access methods as well as some limitations in the base / upstream libraries. I am still working on this.

I propose that all user presets are stored within the same location with a defined path/filename format. This is within our gift and significantly simplifies code. If users need to manipulate presets manually or externally, e.g. on USB drive then we can probably import feature.

**Comment by riban-bw** [comment]
Progress update: git branch [feature/614_preset_management](https://github.com/zynthian/zynthian-ui/tree/feature/614_preset_management) is progressing well. It provides a context menu when bold pressing SELECT on a preset that offers:
- Add to / remove from favourites
- Save preset
- Rename preset
- Delete preset

Rename / delete are only offered for user presets. Favourite management, rename and delete are implemented. Save is not yet implemented.

Save will work like a "save as" function offering to select or create a bank to save the preset to and the ability to name the preset before saving (using on-screen keyboard). This might better be presented from the layer context menu because otherwise a user must edit the sound then navigate to the list of presets and access the context menu from an irrelevant preset. There may be advantage to offering both, i.e. save the current configuration as a new preset (or overwrite existing) and the ability to copy an existing preset though the latter has less benefit - you may as well just load the preset then save as a new one - so probably move "Save" from the preset context menu to the layer/engine context menu.

I hope to have something ready for review later this week but provide this update to allow interested parties to give feedback and influence development.

**Comment by polluxsynth** [comment]
> Save will work like a "save as" function offering to select or create a bank to save the preset to and the ability to name the preset before saving (using on-screen keyboard). This might better be presented from the layer context menu because otherwise a user must edit the sound then navigate to the list of presets and access the context menu from an irrelevant preset. There may be advantage to offering both, i.e. save the current configuration as a new preset (or overwrite existing) and the ability to copy an existing preset though the latter has less benefit - you may as well just load the preset then save as a new one - so probably move "Save" from the preset context menu to the layer/engine context menu.

I think the most common workflow is to want to save a preset after working on it a bit, rather than expressly copying an existing preset to a new location and then proceeding to work on it. So I'd agree with your final conclusion, just have a single 'save' (or 'save as') from the layer/engine context menu. Having it in two places is probably confusing, I think it will create a feeling of ambiguity for users - "are these two functions the same, and why is in two places in that case?".

**Comment by jofemodo** [comment]
I just tested latest changes, including bank managing.

I don't like having 2 entries removing & deleting. It's really confusing and not needed at all.

First, FYI, currently when you remove all presets from a bank, the bank remains hidden. In other words, empty banks are not shown in the list.

You never want to "remove" a bank without deleting the presets inside because it's not clear what happens with its presets. In fact i still don't know where are the presets from the banks i removed while testing ;-)

What you normally want is:

+ Delete a bank and all the presets inside
+ Or rename the bank
+ Or explicitly move the presets inside to other places and then delete the bank. The last is not needed because empty banks are not shown in the "normal" list.

My proposal is:

+ Leave "delete" bank + presets
+ Remove the "remove" option
+ Add "Move to" option to the preset menu
+ Make empty banks to appear in the list when creating a new preset or "moving to".

Optionally we could implement "Move all presets to" in the bank options menu. This would be quite similar to the current "remove" option, but it's explicit regarding the destiny of the moved presets. If you like, we could totally delete the bank so it doesn't appear in any list. The problem with this option is regarding "factory banks" that could contain factory & user presets. We could be more explicit and put: "Move all user presets to" ;-)

Regards,

**Comment by riban-bw** [comment]
I had alrealy changed this before I read you comment! I discussed this in Zynth Club and it became clear what the options should / could be...

The principle behind "Remove" was that you could remove the bank and all the presets would fall out into a catch-all (virtual / None) bank. I we pondering how to implement that. (It is a kinda bug that if there are banks then any presets not in a bank are hidden.) We discussed the idea of using tags rather than / as well as banks. In LV2, banks are effectively just tagged presets. I decided that implementing a tag-based mechanism would require some thought and work so deferred that for a possible future development and simply removed the "Remove" option.

I am not sure we need to "Move" presets. To (mis)quote a wise Spaniard, "Simple is good"! A user can load / save / delete a preset during bank management which does the same thing as move. A bit more arduous but I anticipate this is an infrequent process and users may generally want to consider each preset individually. If users want a move or bulk move feature in the future they can ask for it.

I am using the premis that an empty bank should be deleted and that is what the code does. Let's keep that simple. Don't offer explicit bank deleting, just do it implicitly when a bank is empty. Showing presets that are not in a bank would be advantageous but I am leaving that for a later effort.

**Comment by jofemodo** [comment]
Hi @riban-bw !

I totally agree with you in keeping things simple, so no "move to" options. No "remove" nor "delete" options. This leaves the bank options menu very short: Rename only!

BTW, unbanked presets are shown inside the "None" pseudo-bank. That's done by the cache system (aka webconf's "search for presets button"). I supose the presets from the banks i "removed" must be there ;-)

Regards,

**Comment by riban-bw** [comment]
> unbanked presets are shown inside the "None" pseudo-bank

Yep! I feel that pseudo bank should be exposed. I have considered doing so but not yet tackled it. Not sure what to call it in the UI.

**Comment by jofemodo** [comment]
It seems OK now.
**Note:** if you include the:

`zynthian/zynthian-issue-tracking#614`

label in your commit comment, the commit get attached to the ticket and it's nicer for the discussion.

Like this: https://github.com/zynthian/zynthian-issue-tracking/issues/641

I know you know ;-)

**Comment by riban-bw** [comment]
Cool! This is now merged into _Testing_. I will close this issue and we can track individual improvements or bugs under separate tickets.
