### ISSUE TITLE
zxcv keys do not produce appropriate responses as do S1-S4

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#616]
**Describe the bug**
The 4 S1-S4 switches are able to enact functions as defined ( S3 Audio Record Toggle for example) Do not respond when addressed by a keyboard sending the appropriate keys zxcv or a arduino generated keyboard press.

**To Reproduce**
1. Press s3 (audio record starts)
2. Press s3 (audio record stops)'
3. send keyboard c  (No response)

**Expected behavior**
Sending the correct keyboard codes should operate the function key definition.

**Setup:**
![image](https://user-images.githubusercontent.com/79083/155372940-3fc4997e-1bcc-479b-b464-dd660d25c79a.png)

**Comment by riban-bw** [comment]
The report is a bit confusing. Are you saying that the key bindings for keys, 'z', 'x', 'c' & 'v' are not triggering the correct functions? I don't see how that relates to hardware switches S1-S4.

Please provide the key bindings table for the Zynthian you are experiencing this issue.

**Comment by wyleu** [comment]
Apologies. 
I am attempting to map the audio record toggle action to a remote arduino based device which emits (proved) keyboard presses from a set of s1-s4 switches on the arduino. as per the declared documentation. 

I can toggle the audio record with the appropriate s1-s4, (S3 in this case) switches on the host zynthian but sending the c key does not toggle audio record all other remote encoder functionality occurs ( it's really nice to be able to turn up and down a level from a remote encoder.) 

![image](https://user-images.githubusercontent.com/79083/158983884-5b791aad-d9d0-46c2-8035-a9f9ea750a4f.png)
The encoders work the switches don't.

**Comment by riban-bw** [comment]
I wonder if you may be confusing the mapping? You are able to map hardware switches to perform actions via hardware section of webconf which it seems like you have successfully done.

You can also map keyboard press to actions in the key bindings section of webconf, e.g. mapping key 'c' to record toggle. Has this been done?

**Comment by wyleu** [comment]
I understand that I can map as you describe. I'm ,perhaps, trying to be a little more generic in the overall interface. 
I thought ( but cannot prove) that we implemented the s1-s4 switches as specific key presses. Which means that a remote control device would entirely ape the functionality of the current kit implementations. Which would mean such a device could be plugged in and no further configuration attempted. Least surprise if you will. 
I can't find any mention of the implementation so a solution as you describe should work. But if we are to implement encoder up/down/press it seems to leave out the s1-s4 switches at this level of the interface. 
PErhaps I should reword it as a request the addtion of four keyboard controls for the s1-s4 switch.

Sorry i this seems small minded but it seems a useful level of implementation for little overall coding overhead and would help standardize the hardware control interface. Sorry for not being clearer and obviously in error.

**Comment by riban-bw** [comment]
The four rotary encoders and their associated push buttons are part of the UI. They have context sensitive functions within the UI including navigation, control, etc. The four front panel switches are functional triggers that can perform various operations but are not integrated or directly recognised by the UI. Key binding allows QWERTY (or similar) keys to be bound to various functions including UI and non-UI functions. There is no concept of binding one trigger to another trigger. I feel such abstraction will lead to a level of complexity that will be difficult to maintain and for users to keep a logical understanding. Although a single use-case like you describe may seems simple, as such an interface gets flexed we will soon lose track of what is doing what to what and why.

Sorry - I would classify this as behaviour by design and won't fix - but will leave to @jofemodo to affirm this.

**Comment by wyleu** [comment]
Ok. No problem.

**Comment by wyleu** [comment]
Closed
