### ISSUE TITLE
Website SSL not working

### ISSUE THREAD

**Issue by mxmilkb** [zynthian/zynthian-issue-tracking#82]
**Describe the bug**
https://zynthian.org/ gives

"Secure Connection Failed

An error occurred during a connection to zynthian.org. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG "

**To Reproduce**
1. Go to https://zynthian.org/ in Firefox

**Comment by jofemodo** [comment]
This site doesn't exist, my friend. You should be using: http://zynthian.org
The next version of the project website will work with https, but not this.

**Comment by mxmilkb** [comment]
I guess "web server configuration + LetsEncrypt cron" would be more apt than "site".

Soo.. you will fix it with the next version of the website?

Anyway, your call, I've done my bit.

**Comment by jofemodo** [comment]
Other zynthian "spaces" already use LetsEncrypt. But i don't want to spend 1 minute with this website because:

1. The website only have a basic contact form. Not a real security problem.
2. We are currently working in the new website and it should be ready very soon.

Anyway, thanks for your bit ;-)

**Comment by jofemodo** [comment]
OK @mxmilkb !
You (and some googling about the subject) convinced to me and now everything (web, blog & wiki) is https. 

Thanks a lot!
