### ISSUE TITLE
MIDI Learn not working in MOD-UI

### ISSUE THREAD

**Issue by Jimi-Heinrich** [zynthian/zynthian-issue-tracking#835]
**Describe the bug**
MIDI learn not working in MOD-UI

**To Reproduce**
1. Load MOD-UI instance from snapshot
2. either try to use already learned prms
3. or try assigning new MIDI learn to any prm

**Expected behavior**
MIDI learn should work, new or already assigned

**Setup:**
- Build Date: 2022-11-01
 - Raspberry Pi 4 Model B Rev 1.4
Audio: [HifiBerry DAC+ ADC PRO](http://zynthian.local/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://zynthian.local/hw-display)
Wiring: [MCP23017_ZynScreen](http://zynthian.local/hw-wiring)
I2C: [MCP23017@0x20](http://zynthian.local/hw-wiring)
Profile: [v4_stage](http://zynthian.local/hw-wiring)
 - Raspbian GNU/Linux 10 (buster) 

**Additional context**
you can see the MIDI assignement in the ZynUI, but it doesnt react.

**Comment by steveb** [comment]
I'm seeing this issue also, and the workaround I found was to click on MIDI PORTS in the mod-ui lower right and select Aggregated Mode, Save, then Save the pedalboard.

I don't know if Separated mode is ever useful on a Zynthian hosted environment, we could consider hard-coding midi_aggregated_mode = True always in a host.py patch:
https://github.com/zynthian/mod-ui/blob/zyn-mod-merge-next/mod/host.py#L1145
https://github.com/zynthian/mod-ui/blob/zyn-mod-merge-next/mod/host.py#L3375

**Comment by steveb** [comment]
There might be a bit more going on here, I only get CC messages affecting the plugins when the mod-ui web interface is loaded in the browser, even when forcing midi_aggregated_mode = True in host.py

**Comment by steveb** [comment]
Looking at the patchage graph and trying various combinations of this:

- pedalboard ttl <midi_separated_mode> ingen:value 0 or 1
- changing default aggregated mode in engine enable_midi_devices[1]

The results are not consistent, midi port mod-host:midi_in is either connected to:
1. The raw midi devices, and CC mapping works
2. ZynMidiRouter:ch0_out and no CC values get through
3. No connections at all, and no CC values get through

Should midi be coming out of ZynMidiRouter:ch0_out when midi is going in on the first channel? That might be the best fix but I don't understand the router architecture.

Otherwise I think there is races when mod-ui and the engine set the aggregated mode, and calling enable_midi_devices for every ping isn't always enough to reset it.

That might be all I can do for now, this will need someone like @jofemodo to describe how this should work.

[1] https://github.com/zynthian/zynthian-ui/blob/testing/zyngine/zynthian_engine_modui.py#L695

**Comment by jofemodo** [comment]
It's solved in testing. Please, test and confirm.

**Comment by steveb** [comment]
> It's solved in testing. Please, test and confirm.

I've just tried the zyncoder and zynthian-ui changes and it now works! I'd love these fixes in stable please

**Comment by Jimi-Heinrich** [comment]
After updating the last stable (not testing) I got this when trying to edit MOD-UI on ZynGUI:

![20230131_082858](https://user-images.githubusercontent.com/60140248/215709592-f0df151c-89f4-4627-96fa-94ae08e84d40.jpg)


Every info on prams is gone now.

I guess that is not so good.

**Comment by attila-gabris** [comment]
It works sometimes, not always… I can assingn a parameter to midi, it’s OK. But it only works when I have the web interface connected. If I disconnect, it stops working. After a reboot, if I start web interface first, it works. But if I try the controller before start web interface, it moves a little, but almost immediatly stops, and doesn’t work anymore.
It seems that the midi learning works, but the operation of the assigned controller somehow depends on the connection between Zynthian and the web interface.
I can’t save Aggregated mode. I select it, save it, but in a few seconds Separated mode restore itself(?) and save the pedalboard doesn’t help.
