### ISSUE TITLE
Power save not waking up when CUIA message received.

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-issue-tracking#836]
**Describe the bug**
I am using Zynthian  with an external controller that sends CUIA messages. The problem is that Zynthian is not waking up from power save (blank screen), when a CUIA message is received.

**To Reproduce**
- Wait until screen goes blank.
- Send CUIA message.
- Screen is not waking up.

**Expected behavior**
The screen should wake up the moment a CUIA message is received.

**Setup:**
 - SD-image build 01.11.2022
 - Hardware Config: Pi3, standard PI Touchscreen.

**Comment by mollat** [comment]
I can confirm something similar:

The screensaver will go blank - even while I am switching presets. And then it will not go away turning the knobs.

The knobs - however - still work. So I can push the lower right one to switch it off.

(V4, hardware is 3 weeks old, actual updates.)

**Comment by jofemodo** [comment]
Done! Please test and confirm!

**Comment by mollat** [comment]
It works now to remove the screensaver by turning or pushing a knob. However - touching the touchpad does not remove the screensaver - although the touch goes through the screensaver and changes (silenty) the focus on the mixer bars.

Furthermore - it would be nice if the screensaver would dismiss the first push or move of a knob, so that nothing must be altered while removing the screensaver.

But this is a minor problem. I am fine with this... ;) Thanks!
