### ISSUE TITLE
Add audio device 'Yamaha VKB-100 Vocaloid'

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-issue-tracking#945]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Audio device definition for 'Yamaha VKB-100 Vocaloid' as below
`-P 70 -t 2000 -s -d alsa -d hw:Keyboard -r 44100 -p 256 -n 2 -X raw`

**Comment by riban-bw** [comment]
I feel like the list of devices could have some attention paid. We don't want an endless list of subtly different configurations. Maybe there is an opportunity to have a map of hw names to friendly names so that users can select from the friendly name and the approriate hw: name is used. Maybe that is not much different to a long list of full configs but you might find some common hw for different friendly names, e.g. lots of generic USB audio devices may have a common name.

**Comment by jofemodo** [comment]
Added! We will think about how to rationalize audio & display config, hopefully reducing the long list.
Indeed, perhaps we should think of implementing auto detection+config code.
