### ISSUE TITLE
Disabling MIDI event filtering for chains

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-issue-tracking#957]
**Is your feature request related to a problem? Please describe.**
Some engines do not support sustain pedals. But I need to hold a sound with sustain, so I tried the plugin `TonePedal` from x42 midifilters (currently you have to install them by yourself because falkTX's repository has an older version) as MIDI-FX before NoizeMaker. This does not work because MIDI-CCs are filtered (due the need of MIDI-learning).

**Describe the solution you'd like**
Maybe it is possible to disabled filtering of MIDI events or to create a list which events should be filtered (or not filtered) for a chain.

**Describe alternatives you've considered**
A MIDI chain with MIDI-cloning to the NoizeMaker chain does also not work. Only in MOD-UI it seems to do what I expect.

**Additional context**
See [Zynthian-Forum](https://discourse.zynthian.org/t/bug-in-midi-fx-chain/9167)

**Comment by jofemodo** [comment]
Hi @dcoredump !

This is fixed in oram:

+ MIDI chains route ALL events for the selected channel. Note that you can select "All Channels" in MIDI chains.
+ Synth chains now have a new "CC route" option that you can use for routing the selected CC numbers. Please, note that this can create bizarre issues when used with MIDI-controlled engines:

+ FluidSynth
+ Linuxsampler
+ Sfizz
+ ZynAddSubFX
+ setBfree
+ Pianoteq => Specially this because it uses almost all CC numbers!

In the other hand it should work quite nicely with most "LV2" engines, given that you don't route CCs already learned.
Freedom is dangerous, my friend ;-)

Regards!
