### ISSUE TITLE
Creeping Master Fader in Mixer with <> QWERTY use.

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#968]
**Describe the bug**
Heavy use of the < >   Qwerty

**To Reproduce**
1. Go to Mixer
2. Plug in Qwerty Keyboard
3. Hold Down Shift key 
4. Rapidly Press < & > keys
5. Triggers master Fader or selected fader increasing to maximum or decreasing to minimum. 

**Expected behavior**
The fader should remain in its last setting.

**Setup:**
zyncoder: [oram (9ea5d33)]
zynthian-ui: [oram (5d7a3d5)]
zynthian-sys: [oram (ee85416)]
zynthian-data: [oram (64c5f91)]
zynthian-webconf: [oram (9093d3f]

**Additional context**
This is the mechanism used by my remote control device and the effect occurs  instantly if an attempt is made to alter the fader level.

It also gets saved as Last State if you shut down, using zynthian mechanisms. Which means you start up with either a silent instrument of at full volume. A rebbot is the only thing that clears it.

**Comment by riban-bw** [comment]
This is related to keyboard autorepeat function. Some key event seems to be missed or processed incorrectly so the key release fails to cancel autorepeat.

**Comment by riban-bw** [comment]
I have seen this happen when a key modifier is used then the modifier is released before the key, e.g. shift+. to activate encoder up then release shift then release '.' - the key release for '>' is never received. Please check if this could be the cause of the problem, e.g. your USB HID hardware controller may be sending out the key events in the wrong order. (It's worth checking!)

**Comment by riban-bw** [comment]
I have looked at the code and understand why this happens.

- Press SHIFT - produces unmapped keycode - ignored
- Press ">" - produces keycode that is mapped to encoder 2 UP start
- Release SHIFT - produces unnapped keycode - ignored
- Release "." - produces keycode that is mapped to encoder 3 UP end

It is not easy to change this behaviour due to the keymapping being transitory so there is not an easily accessible, persistent state of each encoder and the mapping results in the designed behaviour.

Knowing this behaviour on a QWERTY keyboard allows the user to use (and abuse) it correctly, e.g. it is possible to lock an encoder in its forward winding state if desired. Hardware that uses USB HID interface should be coded to give expected behaviour, e.g. should release action key before modifier key (or at least send a single command that includes the modifier state).

I am going to mark this issue as resolved because the system is behaving as designed and it is challenging to change that design. If this issue becomes more invasive we can revisit.
